crud_test/src/Entity/Art.php
<?php

namespace App\Entity;

use App\Repository\ArtRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtRepository::class)]
class Art
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\ManyToOne(inversedBy: 'Art')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Artist $Artist = null;

    #[ORM\Column]
    private ?bool $isAvailable = null;

    #[ORM\OneToMany(mappedBy: 'Art', targetEntity: SaleEventEntry::class, orphanRemoval: true)]
    private Collection $saleEventEntries;

    #[ORM\OneToMany(mappedBy: 'art', targetEntity: Order::class)]
    private Collection $orders;

    public function __construct()
    {
        $this->saleEventEntries = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->Artist;
    }

    public function setArtist(?Artist $Artist): self
    {
        $this->Artist = $Artist;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    /**
     * @return Collection<int, SaleEventEntry>
     */
    public function getSaleEventEntries(): Collection
    {
        return $this->saleEventEntries;
    }

    public function addSaleEventEntry(SaleEventEntry $saleEventEntry): self
    {
        if (!$this->saleEventEntries->contains($saleEventEntry)) {
            $this->saleEventEntries->add($saleEventEntry);
            $saleEventEntry->setArt($this);
        }

        return $this;
    }

    public function removeSaleEventEntry(SaleEventEntry $saleEventEntry): self
    {
        if ($this->saleEventEntries->removeElement($saleEventEntry)) {
            // set the owning side to null (unless already changed)
            if ($saleEventEntry->getArt() === $this) {
                $saleEventEntry->setArt(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return "\"".$this->getTitle() ."\" by ". $this->getArtist();
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setArt($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getArt() === $this) {
                $order->setArt(null);
            }
        }

        return $this;
    }
}

crud_test/src/Form/ArtType.php
<?php

namespace App\Form;

use App\Entity\Art;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('year')
            ->add('price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Art::class,
        ]);
    }
}

crud_test/src/Controller/ArtController.php
<?php

namespace App\Controller;

use App\Entity\Art;
use App\Form\Art2Type;
use App\Repository\ArtRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


#[Route('/art')]
class ArtController extends AbstractController
{
    #[Route('/', name: 'app_art_index', methods: ['GET'])]
    public function index(ArtRepository $artRepository): Response
    {
        return $this->render('art/index.html.twig', [
            'art' => $artRepository->findAll(),
            'userRoles' => $this->getUser()->getRoles()
        ]);
    }

    #[Route('/artlist', name: 'app_art_artlist', methods: ['GET'])]
    #[IsGranted('ROLE_CUSTOMER')]
    public function artlist(ArtRepository $artRepository): Response
    {
        $allArt = $artRepository->findAll();
        $artForSaleEvent = [];
        $saleEvet = '';
        foreach ($allArt as $art){
            foreach ($art->getSaleEventEntries() as $entry){
                if($entry->getSaleEvent()->getId() == $_GET["saleEventId"]){
                    $artForSaleEvent[] = $art;
                    $saleEvent = $entry->getSaleEvent()->getName();
                }
            }
        }

        return $this->render('art/artlist.html.twig', [
            'art' => $artForSaleEvent,
            'userRoles' => $this->getUser()->getRoles(),
            'saleEvent' => $saleEvent,
        ]);
    }

    #[Route('/new', name: 'app_art_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_SALES')]
    public function new(Request $request, ArtRepository $artRepository): Response
    {
        $art = new Art();
        $form = $this->createForm(Art2Type::class, $art);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artRepository->save($art, true);

            return $this->redirectToRoute('app_art_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('art/new.html.twig', [
            'art' => $art,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_art_show', methods: ['GET'])]
    public function show(Art $art): Response
    {
        return $this->render('art/show.html.twig', [
            'art' => $art,
            'userRoles' => $this->getUser()->getRoles(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_art_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_SALES')]
    public function edit(Request $request, Art $art, ArtRepository $artRepository): Response
    {
        $form = $this->createForm(Art2Type::class, $art);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artRepository->save($art, true);

            return $this->redirectToRoute('app_art_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('art/edit.html.twig', [
            'art' => $art,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_art_delete', methods: ['POST'])]
    #[IsGranted('ROLE_SALES')]
    public function delete(Request $request, Art $art, ArtRepository $artRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$art->getId(), $request->request->get('_token'))) {
            $artRepository->remove($art, true);
        }

        return $this->redirectToRoute('app_art_index', [], Response::HTTP_SEE_OTHER);
    }
}

crud_test/templates/art/_delete_form.html.twig
<form method="post" action="{{ path('app_art_delete', {'id': art.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ art.id) }}">
    <button class="btn">Delete</button>
</form>

crud_test/templates/art/artlist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Art index{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Art index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Year</th>
            <th>Price</th>
            <th>Sale Event</th>
            <th>IsAvailable</th>
            <th>Artist</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for art in art %}
            <tr>
                <td>{{ art.id }}</td>
                <td>{{ art.title }}</td>
                <td>{{ art.description }}</td>
                <td>{{ art.year }}</td>
                <td>{{ art.price }}</td>
                <td>{{ saleEvent }}</td>
                <td>{{ art.isAvailable ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_artist_show', {'id': art.artist.id}) }}">{{ art.artist }}</a>
                </td>
                <td>
                    <a href="{{ path('app_order_new', {'artId': art.id}) }}">place order</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

crud_test/templates/art/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Art{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Edit Art</h1>

    {{ include('art/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_art_index') }}">back to list</a>

    {{ include('art/_delete_form.html.twig') }}
{% endblock %}

crud_test/templates/art/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Art index{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Art index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Year</th>
                <th>Price</th>
                <th>IsAvailable</th>
                <th>Artis</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for art in art %}
            <tr>
                <td>{{ art.id }}</td>
                <td>{{ art.title }}</td>
                <td>{{ art.description }}</td>
                <td>{{ art.year }}</td>
                <td>{{ art.price }}</td>
                <td>{{ art.isAvailable ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_artist_show', {'id': art.artist.id}) }}">{{ art.artist }}</a>
                </td>
                <td>
                    <a href="{{ path('app_art_show', {'id': art.id}) }}">show</a>
                    <a href="{{ path('app_art_edit', {'id': art.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_art_new') }}">Create new</a>
{% endblock %}

crud_test/templates/art/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Art{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Create new Art</h1>

    {{ include('art/_form.html.twig') }}

    <a href="{{ path('app_art_index') }}">back to list</a>
{% endblock %}

crud_test/templates/art/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Art{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Art</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ art.id }}</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ art.title }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ art.description }}</td>
        </tr>
        <tr>
            <th>Year</th>
            <td>{{ art.year }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ art.price }}</td>
        </tr>
        <tr>
            <th>IsAvailable</th>
            <td>{{ art.isAvailable ? 'Yes' : 'No' }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('app_art_index') }}">back to list</a>

    {% if 'ROLE_SALES' in userRoles %}
        <a href="{{ path('app_art_edit', {'id': art.id}) }}">edit</a>
        {{ include('art/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}