crud_test/src/Entity/SaleEventEntry.php
<?php

namespace App\Entity;

use App\Repository\SaleEventEntryRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SaleEventEntryRepository::class)]
class SaleEventEntry
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'saleEventEntries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SaleEvent $SaleEvent = null;

    #[ORM\ManyToOne(inversedBy: 'saleEventEntries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Art $Art = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSaleEvent(): ?SaleEvent
    {
        return $this->SaleEvent;
    }

    public function setSaleEvent(?SaleEvent $SaleEvent): self
    {
        $this->SaleEvent = $SaleEvent;

        return $this;
    }

    public function getArt(): ?Art
    {
        return $this->Art;
    }

    public function setArt(?Art $Art): self
    {
        $this->Art = $Art;

        return $this;
    }
}

crud_test/src/Form/SaleEventEntryType.php
<?php

namespace App\Form;

use App\Entity\SaleEventEntry;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SaleEventEntryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('SaleEvent')
            ->add('Art')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SaleEventEntry::class,
        ]);
    }
}

crud_test/src/Controller/SaleEventEntryController.php
<?php

namespace App\Controller;

use App\Entity\SaleEventEntry;
use App\Form\SaleEventEntryType;
use App\Repository\SaleEventEntryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_SALES')]

#[Route('/sale/evententry')]
class SaleEventEntryController extends AbstractController
{
    #[Route('/', name: 'app_sale_event_entry_index', methods: ['GET'])]
    public function index(SaleEventEntryRepository $saleEventEntryRepository): Response
    {
        return $this->render('sale_event_entry/index.html.twig', [
            'sale_event_entries' => $saleEventEntryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_sale_event_entry_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SaleEventEntryRepository $saleEventEntryRepository): Response
    {
        $saleEventEntry = new SaleEventEntry();
        $form = $this->createForm(SaleEventEntryType::class, $saleEventEntry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $saleEventEntryRepository->save($saleEventEntry, true);

            return $this->redirectToRoute('app_sale_event_entry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sale_event_entry/new.html.twig', [
            'sale_event_entry' => $saleEventEntry,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_sale_event_entry_show', methods: ['GET'])]
    public function show(SaleEventEntry $saleEventEntry): Response
    {
        return $this->render('sale_event_entry/show.html.twig', [
            'sale_event_entry' => $saleEventEntry,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_sale_event_entry_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SaleEventEntry $saleEventEntry, SaleEventEntryRepository $saleEventEntryRepository): Response
    {
        $form = $this->createForm(SaleEventEntryType::class, $saleEventEntry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $saleEventEntryRepository->save($saleEventEntry, true);

            return $this->redirectToRoute('app_sale_event_entry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sale_event_entry/edit.html.twig', [
            'sale_event_entry' => $saleEventEntry,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_sale_event_entry_delete', methods: ['POST'])]
    public function delete(Request $request, SaleEventEntry $saleEventEntry, SaleEventEntryRepository $saleEventEntryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$saleEventEntry->getId(), $request->request->get('_token'))) {
            $saleEventEntryRepository->remove($saleEventEntry, true);
        }

        return $this->redirectToRoute('app_sale_event_entry_index', [], Response::HTTP_SEE_OTHER);
    }
}

crud_test/templates/sale_event_entry/_delete_form.html.twig
<form method="post" action="{{ path('app_sale_event_entry_delete', {'id': sale_event_entry.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sale_event_entry.id) }}">
    <button class="btn">Delete</button>
</form>

crud_test/templates/sale_event_entry/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SaleEventEntry{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Edit SaleEventEntry</h1>

    {{ include('sale_event_entry/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_sale_event_entry_index') }}">back to list</a>

    {{ include('sale_event_entry/_delete_form.html.twig') }}
{% endblock %}

crud_test/templates/sale_event_entry/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SaleEventEntry index{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>SaleEventEntry index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Event</th>
                <th>Art</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sale_event_entry in sale_event_entries %}
            <tr>
                <td>{{ sale_event_entry.id }}</td>
                <td>
                    <a href="{{ path('app_sale_event_show', {'id': sale_event_entry.saleEvent.id}) }}">{{ sale_event_entry.saleEvent }}</a>
                </td>
                <td>
                    <a href="{{ path('app_art_show', {'id': sale_event_entry.art.id}) }}">{{ sale_event_entry.art }}</a>
                </td>
                <td>
                    <a href="{{ path('app_sale_event_entry_show', {'id': sale_event_entry.id}) }}">show</a>
                    <a href="{{ path('app_sale_event_entry_edit', {'id': sale_event_entry.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_sale_event_entry_new') }}">Create new</a>
{% endblock %}

crud_test/templates/sale_event_entry/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SaleEventEntry{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>Create new SaleEventEntry</h1>

    {{ include('sale_event_entry/_form.html.twig') }}

    <a href="{{ path('app_sale_event_entry_index') }}">back to list</a>
{% endblock %}

crud_test/templates/sale_event_entry/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SaleEventEntry{% endblock %}

{% block body %}
    {% include 'default/nav.html.twig' %}

    <h1>SaleEventEntry</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sale_event_entry.id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_sale_event_entry_index') }}">back to list</a>

    <a href="{{ path('app_sale_event_entry_edit', {'id': sale_event_entry.id}) }}">edit</a>

    {{ include('sale_event_entry/_delete_form.html.twig') }}
{% endblock %}